variables:
  REGION: us-east-2
  DOCKER_HOST: tcp://docker:2375
  EC_REGISTRY: 581303157279.dkr.ecr.us-east-2.amazonaws.com
stages:
  - dev-build & publish
  - qa-build & publish
  - uat-build & publish
  
dev-build-publish:
  image: docker:latest
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  stage: dev-build & publish
  services:
    - docker:dind
  before_script: 
    - amazon-linux-extras install docker
  script:
    - docker build -t $EC_REGISTRY/$CI_PROJECT_NAME:"$CI_PIPELINE_ID" .
    - docker images
    - aws ecr get-login-password --region $REGION| docker login --username AWS --password-stdin $EC_REGISTRY
    - aws ecr create-repository --repository-name $CI_PROJECT_NAME --image-scanning-configuration scanOnPush=true --region $REGION --image-tag-mutability MUTABLE || true 
    - docker push $EC_REGISTRY/$CI_PROJECT_NAME:"$CI_PIPELINE_ID"
  when: manual
  only:
    - develop
qa-build-publish:
  image: docker:latest
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  stage: qa-build & publish
  services:
    - docker:dind
  before_script: 
    - amazon-linux-extras install docker
  script:
    - docker build --build-arg ENV_VAR=qa -t $EC_REGISTRY/promt-qa/$CI_PROJECT_NAME:"$CI_PIPELINE_ID" .
    - docker images
    - aws ecr get-login-password --region $REGION| docker login --username AWS --password-stdin $EC_REGISTRY
    - aws ecr create-repository --repository-name promt-qa/$CI_PROJECT_NAME --image-scanning-configuration scanOnPush=true --region $REGION --image-tag-mutability MUTABLE || true 
    - docker push $EC_REGISTRY/promt-qa/$CI_PROJECT_NAME:"$CI_PIPELINE_ID"
  when: manual
  only:
    - develop
uat-build-publish:
  image: docker:latest
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  stage: uat-build & publish
  services:
    - docker:dind
  before_script: 
    - amazon-linux-extras install docker
  script:
    - docker build --build-arg ENV_VAR=uat-friday -t $EC_REGISTRY/promt-uat/$CI_PROJECT_NAME:"$CI_PIPELINE_ID" .
    - docker images
    - aws ecr get-login-password --region $REGION| docker login --username AWS --password-stdin $EC_REGISTRY
    - aws ecr create-repository --repository-name promt-uat/$CI_PROJECT_NAME --image-scanning-configuration scanOnPush=true --region $REGION --image-tag-mutability MUTABLE || true 
    - docker push $EC_REGISTRY/promt-uat/$CI_PROJECT_NAME:"$CI_PIPELINE_ID"
  when: manual
  only:
    - release/uat
